before_script:
    - angr-test sync hard

### local
cle:
    script: "angr-test cle"
    tags: [angr]

lint:
    script: "angr-test lint"
    tags: [angr]

### first level
angr:
    script: "angr-test angr"
    tags: [angr]

fidget:
    script: "angr-test fidget"
    tags: [angr]

angrop:
    script: "angr-test angrop"
    tags: [angr]

tracer:
    script: "angr-test tracer"
    tags: [angr]

docs:
    script: "angr-test docs"
    tags: [angr]

### other levels
topsecret:
    script: "angr-test top-secret"
    tags: [angr]

rex:
    script: "angr-test rex"
    tags: [angr]

driller:
    script: "angr-test driller"
    tags: [angr]

patcherex:
    script: "angr-test patcherex"
    tags: [angr]
